### ISSUE TITLE
compatiblityproblems with addon FleshWindow

### ISSUE THREAD

**Issue by Vargoth86** [napnapnapnap/wowsimsexporter-wotlk-335#1]
When i try to type in /wse the Window open but its empty and these luaerror occures

Message: Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:427: attempt to index field '?' (a nil value)
Time: 03/09/23 12:22:21
Count: 1
Stack: [C]: ?
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:427: in function `GetOrderedTalentInfo'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:128: in function `CreateTalentEntry'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:196: in function `GetGearEnchantGems'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:327: in function `l_Generate'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:335: in function `CreateWindow'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:165: in function `?'
...s\FlashWindow\Libs\AceConsole-3.0\AceConsole-3.0.lua:94: in function `value'
Interface\FrameXML\ChatFrame.lua:4070: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:3660: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:3698: in function <Interface\FrameXML\ChatFrame.lua:3694>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: 

Message: Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:427: attempt to index field '?' (a nil value)
Time: 03/09/23 12:28:26
Count: 2
Stack: [C]: ?
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:427: in function `GetOrderedTalentInfo'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:128: in function `CreateTalentEntry'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:196: in function `GetGearEnchantGems'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:327: in function `l_Generate'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:335: in function `CreateWindow'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:167: in function `?'
...s\FlashWindow\Libs\AceConsole-3.0\AceConsole-3.0.lua:94: in function `?'
Interface\FrameXML\ChatFrame.lua:4049: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:3660: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:3698: in function <Interface\FrameXML\ChatFrame.lua:3694>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: 

Message: Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:427: attempt to index field '?' (a nil value)
Time: 03/09/23 13:15:14
Count: 3
Stack: [C]: ?
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:427: in function `GetOrderedTalentInfo'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:128: in function `CreateTalentEntry'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:196: in function `GetGearEnchantGems'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:327: in function `l_Generate'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:335: in function `CreateWindow'
Interface\AddOns\WowSimsExporter\WowSimsExporter.lua:165: in function `?'
...s\FlashWindow\Libs\AceConsole-3.0\AceConsole-3.0.lua:94: in function `?'
Interface\FrameXML\ChatFrame.lua:4049: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:3660: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:3698: in function <Interface\FrameXML\ChatFrame.lua:3694>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:

**Comment by napnapnapnap** [comment]
Should be fixed now, I tried will multiple characters and addons, @Vargoth86 please confirm it works on your end.
