### ISSUE TITLE
Problems with import Strings

### ISSUE THREAD

**Issue by Vargoth86** [napnapnapnap/wowsimsexporter-wotlk-335#2]
when i import the ingamestring to the Simulator this massage occures

Import error: SyntaxError: Unexpected non-whitespace character after JSON at position 1186

**Comment by napnapnapnap** [comment]
could you provide your export string?

**Comment by Vargoth86** [comment]
sure

{"talents":"203005033100030000000000000000-0055030012303330053120300351-0000000000000000000000000000","glyphs":{"major":["Glyph of Living Bomb","Glyph of Fireball","Glyph of Molten Armor"],"minor":["Glyph of Arcane Intellect","Glyph of Slow Fall","Glyph of Frost Ward"]},"class":"mage","race":"Troll","name":"Vargoth","gear":{"items":[{"enchant":3820,"gems":[41285,40133],"id":51281},{"enchant":0,"gems":[40133],"id":50724},{"enchant":3810,"gems":[40153],"id":51284},{"enchant":3722,"gems":[40113],"id":54583},{"enchant":1144,"gems":[40113,40133,40153],"id":50629},{"enchant":2332,"gems":[40113],"id":54582},{"enchant":3604,"gems":[40133],"id":51280},{"enchant":0,"gems":[40133,40113,40113],"id":50613},{"enchant":3872,"gems":[40133,40153],"id":51282},{"enchant":3606,"gems":[40133,40113],"id":50699},{"enchant":3840,"gems":[40152],"id":50398},{"enchant":3840,"gems":[40133],"id":50664},{"enchant":0,"gems":[],"id":50365},{"enchant":0,"gems":[],"id":54588},{"enchant":3834,"gems":[40113],"id":50732},{"enchant":0,"gems":[],"id":50719},{"enchant":0,"gems":[40152],"id":50684}]},"professions":[{"name":"Engineering","level":450},{"name":"Tailoring","level":450}],"level":80,"spec":"arcane"}{"talents":"203005033100030000000000000000-0055030012303330053120300351-0000000000000000000000000000","glyphs":{"major":["Glyph of Living Bomb","Glyph of Fireball","Glyph of Molten Armor"],"minor":["Glyph of Arcane Intellect","Glyph of Slow Fall","Glyph of Frost Ward"]},"class":"mage","race":"Troll","name":"Vargoth","gear":{"items":[{"enchant":3820,"gems":[41285,40133],"id":51281},{"enchant":0,"gems":[40133],"id":50724},{"enchant":3810,"gems":[40153],"id":51284},{"enchant":3722,"gems":[40113],"id":54583},{"enchant":1144,"gems":[40113,40133,40153],"id":50629},{"enchant":2332,"gems":[40113],"id":54582},{"enchant":3604,"gems":[40133],"id":51280},{"enchant":0,"gems":[40133,40113,40113],"id":50613},{"enchant":3872,"gems":[40133,40153],"id":51282},{"enchant":3606,"gems":[40133,40113],"id":50699},{"enchant":3840,"gems":[40152],"id":50398},{"enchant":3840,"gems":[40133],"id":50664},{"enchant":0,"gems":[],"id":50365},{"enchant":0,"gems":[],"id":54588},{"enchant":3834,"gems":[40113],"id":50732},{"enchant":0,"gems":[],"id":50719},{"enchant":0,"gems":[40152],"id":50684}]},"professions":[{"name":"Engineering","level":450},{"name":"Tailoring","level":450}],"level":80,"spec":"arcane"}{"talents":"203005033100030000000000000000-0055030012303330053120300351-0000000000000000000000000000","glyphs":{"major":["Glyph of Living Bomb","Glyph of Fireball","Glyph of Molten Armor"],"minor":["Glyph of Arcane Intellect","Glyph of Slow Fall","Glyph of Frost Ward"]},"class":"mage","race":"Troll","name":"Vargoth","gear":{"items":[{"enchant":3820,"gems":[41285,40133],"id":51281},{"enchant":0,"gems":[40133],"id":50724},{"enchant":3810,"gems":[40153],"id":51284},{"enchant":3722,"gems":[40113],"id":54583},{"enchant":1144,"gems":[40113,40133,40153],"id":50629},{"enchant":2332,"gems":[40113],"id":54582},{"enchant":3604,"gems":[40133],"id":51280},{"enchant":0,"gems":[40133,40113,40113],"id":50613},{"enchant":3872,"gems":[40133,40153],"id":51282},{"enchant":3606,"gems":[40133,40113],"id":50699},{"enchant":3840,"gems":[40152],"id":50398},{"enchant":3840,"gems":[40133],"id":50664},{"enchant":0,"gems":[],"id":50365},{"enchant":0,"gems":[],"id":54588},{"enchant":3834,"gems":[40113],"id":50732},{"enchant":0,"gems":[],"id":50719},{"enchant":0,"gems":[40152],"id":50684}]},"professions":[{"name":"Engineering","level":450},{"name":"Tailoring","level":450}],"level":80,"spec":"arcane"}

**Comment by napnapnapnap** [comment]
Ok I see what happened, by typing multiple times /wse or hit the generate button it added the export string multiple times, your string has 3 export strings.

The correct one is : 

```
{"talents":"203005033100030000000000000000-0055030012303330053120300351-0000000000000000000000000000","glyphs":{"major":["Glyph of Living Bomb","Glyph of Fireball","Glyph of Molten Armor"],"minor":["Glyph of Arcane Intellect","Glyph of Slow Fall","Glyph of Frost Ward"]},"class":"mage","race":"Troll","name":"Vargoth","gear":{"items":[{"enchant":3820,"gems":[41285,40133],"id":51281},{"enchant":0,"gems":[40133],"id":50724},{"enchant":3810,"gems":[40153],"id":51284},{"enchant":3722,"gems":[40113],"id":54583},{"enchant":1144,"gems":[40113,40133,40153],"id":50629},{"enchant":2332,"gems":[40113],"id":54582},{"enchant":3604,"gems":[40133],"id":51280},{"enchant":0,"gems":[40133,40113,40113],"id":50613},{"enchant":3872,"gems":[40133,40153],"id":51282},{"enchant":3606,"gems":[40133,40113],"id":50699},{"enchant":3840,"gems":[40152],"id":50398},{"enchant":3840,"gems":[40133],"id":50664},{"enchant":0,"gems":[],"id":50365},{"enchant":0,"gems":[],"id":54588},{"enchant":3834,"gems":[40113],"id":50732},{"enchant":0,"gems":[],"id":50719},{"enchant":0,"gems":[40152],"id":50684}]},"professions":[{"name":"Engineering","level":450},{"name":"Tailoring","level":450}],"level":80,"spec":"arcane"}
```

I'll try to fix this issue but the addon is still usable, thanks for your feedback

**Comment by Vargoth86** [comment]
thanks for your work
